package helper

import (
	"bytes"
	"os/exec"

	"github.com/openset/leetcode/internal/base"
)

var CmdHelper = &base.Command{
	Run:       runHelper,
	UsageLine: "helper",
	Short:     "build helper file",
	Long:      "build helper README.md file.",
}

func runHelper(cmd *base.Command, args []string) {
	if len(args) != 0 {
		cmd.Usage()
	}
	var bf bytes.Buffer
	bf.WriteString("<!--|This file generated by command(leetcode helper); DO NOT EDIT.         |-->")
	bf.WriteString(base.AuthInfo)
	bf.WriteString("\n# Helper\n\n")
	bf.WriteString("```text\n")
	out, err := exec.Command(base.CmdName).Output()
	base.CheckErr(err)
	bf.Write(out)
	bf.WriteString("```\n")
	base.FilePutContents("helper/README.md", bf.Bytes())
}
